services:
  - type: worker
    name: my-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python Test9.py"
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false   # أضف التوكن من لوحة Render
